# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-17 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interface_platform', '__first__'),
        ('account', '0002_fix_str'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiteReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField()),
                ('rerun', models.SmallIntegerField()),
                ('count', models.IntegerField()),
                ('duration', models.DurationField()),
                ('passed', models.IntegerField()),
                ('failed', models.IntegerField()),
                ('skipped', models.IntegerField()),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner', to='account.Account', verbose_name=b'runner')),
            ],
        ),
        migrations.CreateModel(
            name='SuiteTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField()),
                ('parent', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
                ('key', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roots', models.ManyToManyField(related_name='roots', to='execution.SuiteTree', verbose_name=b'roots')),
            ],
        ),
        migrations.AddField(
            model_name='suitereport',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_report', to='execution.TestSuite', verbose_name=b'suite_report'),
        ),
    ]
