# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-17 09:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interface_platform', '__first__'),
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='interface_platform.Project'),
            preserve_default=False,
        ),
    ]
